services:
  api:
    build: .
    command: uvicorn apps.erp_api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/cfdi
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=devsecret
    depends_on:
      - db
      - redis
  worker:
    build: .
    command: python -m apps.sync_worker.worker
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/cfdi
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cfdi
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
